# Build configuration for https://tea-ci.org
# Tea CI is a fork of Drone CI with Cygwin/Msys2 support
# Feel free to share Tea CI to more open source developers
# https://docs.tea-ci.org/usage/overview/

debug: true

build:
  compile:
    image: teaci/cygwin$$arch
    pull: true
    shell: cygwin$$arch
    commands:
      - C:/cygwin-installer.exe --site http://mirrors.tea-ci.org/cygwin --local-package-dir Z:/tmp/cygwin -W -P gettext-devel,zlib-devel,libiconv,libiconv-devel,mingw64-i686-gcc-g++,mingw64-i686-zlib,mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,mingw64-x86_64-zlib,dejagnu,dblatex,docbook-xml45,docbook-xsl,xmlto -q &> /dev/null
      - srcdir=`pwd`
      - builddir=/oss/build-stage2
      - installdir=/oss/install-stage2
      - mkdir ${builddir} ${installdir}
      - cd ${builddir}
      - ${srcdir}/configure --prefix=${installdir} -v
      - make
      - make install

  install:
    image: teaci/cygwin$$arch
    pull: true
    shell: cygwin$$arch
    commands:
      - sha1sum /oss/install-stage1/bin/cygwin1.dll /bin/cygwin1.dll
      - cp -vf /oss/install-stage1/cygwin/winsup/cygwin/cygwin1.dll /bin/cygwin1.dll

  test:
    image: teaci/cygwin$$arch
    pull: true
    shell: cygwin$$arch
    commands:
      - sha1sum /bin/cygwin1.dll
      - srcdir=`pwd`
      - builddir=/oss/build-stage2
      - installdir=/oss/install-stage2
      - mkdir ${builddir} ${installdir}
      - cd ${builddir}
      - ${srcdir}/configure --prefix=${installdir} -v
      - make
      - make install

matrix:
  arch:
    - 64
    - 32
